spring:
  application:
    name: daedalus
  profiles:
    active: local
  main:
    banner-mode: OFF
  datasource:
    url: jdbc:postgresql://localhost:5434/daedalusdb?user=daedalususer&password=TestMeMyTest!1
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      keepalive-time: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      validation-timeout: 300000